const FPV_CAM={cx:640,topY:940,depthK:-650,k:840,kpad:0.64,dOff:0.25,eyeH:0.30};
const P=(u,d,h)=>{const dd=Math.max(0.02,d-FPV_CAM.dOff);const sc=FPV_CAM.k/(dd+FPV_CAM.kpad);
  return [FPV_CAM.cx+u*sc,FPV_CAM.topY+dd*FPV_CAM.depthK+(FPV_CAM.eyeH-h)*sc,sc];};
const B={lift:0.15,chin:1.60,shoulder:1.46,shHalf:0.168};
const bdy=1.009;
const hp=P(0,B.chin+0.02,B.lift+0.055);
const hs=(hp[2]/430)*0.44;
const squashY=0.86;
const hx=hp[0], hy=hp[1];
console.log('head anchor y=',hy.toFixed(1),' hs=',hs.toFixed(4),' squashY=',squashY);
const shL=P(B.shHalf*bdy,B.shoulder,B.lift), shR=P(-B.shHalf*bdy,B.shoulder,B.lift);
console.log('shL y=',shL[1].toFixed(1),' shR y=',shR[1].toFixed(1),' sep=',(shL[0]-shR[0]).toFixed(1));
const _sy=hs*squashY, _sx=hs;
const nkBaseY=((shL[1]+shR[1])/2-hy)/_sy;
const nkHalf=Math.abs(shL[0]-shR[0])/2/_sx;
console.log('nkBaseY(local)=',nkBaseY.toFixed(1),'  -> on screen =',(hy+nkBaseY*_sy).toFixed(1));
console.log('nkHalf(local)=',nkHalf.toFixed(1),'  -> screen halfwidth =',(nkHalf*_sx).toFixed(1),'px  (full neck width',(2*nkHalf*_sx).toFixed(0),'px)');
console.log('nkHalfN after clamp*0.68 =', Math.max(30,Math.min(130,nkHalf*0.68)).toFixed(1), '-> screen', (Math.max(30,Math.min(130,nkHalf*0.68))*_sx).toFixed(1));
console.log('neck screen height = ',(nkBaseY)*_sy,'px  (from y',hy.toFixed(0),'to',(hy+nkBaseY*_sy).toFixed(0),')');
