const FPV_CAM={cx:640,topY:940,depthK:-650,k:840,kpad:0.64,dOff:0.25,eyeH:0.30};
const P=(u,d,h)=>{const dd=Math.max(0.02,d-FPV_CAM.dOff);const sc=FPV_CAM.k/(dd+FPV_CAM.kpad);
  return [FPV_CAM.cx+u*sc,FPV_CAM.topY+dd*FPV_CAM.depthK+(FPV_CAM.eyeH-h)*sc,sc];};
const B={shoulder:1.46,hip:0.86,mon:0.92,lift:0.15,shHalf:0.168};
const bdy=1.009;
console.log('--- CURRENT arm code (elD/haD go BEYOND the shoulder) ---');
let el=P(0.255*bdy, B.shoulder+0.20, B.lift-0.055);
let ha=P(0.205*bdy, B.shoulder+0.40, B.lift-0.045);
console.log('shoulder', P(B.shHalf*bdy,B.shoulder,B.lift).map(v=>v.toFixed(0)).join(','));
console.log('elbow   ', el.map(v=>v.toFixed(0)).join(','), '  <-- y should be positive');
console.log('wrist   ', ha.map(v=>v.toFixed(0)).join(','), '  <-- OFF SCREEN TOP');
console.log('\n--- PROPOSED: arms run TOWARD the lens (down her body) ---');
el=P(0.232*bdy, B.shoulder-0.30, B.lift-0.075);
ha=P(0.212*bdy, B.shoulder-0.56, B.lift-0.065);
console.log('elbow   ', el.map(v=>v.toFixed(0)).join(','));
console.log('wrist   ', ha.map(v=>v.toFixed(0)).join(','));
console.log('hipR    ', P(B.hipHalf?0.151:bdy*0.15,B.hip,B.lift).map(v=>v.toFixed(0)).join(','));
